<a href="https://colab.research.google.com/github/MattWang-Portfolio/data-processing-bike/blob/main/bike_iphy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pylab
import calendar
import numpy as np
import pandas as pd
import seaborn as sn
from scipy import stats
import missingno as msno
from datetime import datetime
import matplotlib.pyplot as plt
import warnings
import seaborn as sns
pd.options.mode.chained_assignment = None
warnings.filterwarnings("ignore", category=DeprecationWarning)
%matplotlib inline
#這邊是在import會用到的東西

In [ ]:
train = pd.read_csv('/content/bike/train.csv')
#這是我放在colab的路徑

In [ ]:
train.head()#可看到前五筆資料

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3  2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4  2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1

In [ ]:
train[train.duplicated()] 
#前面都在看跟整理資料(資料預處理)，下面的順序是下面的順序是決策樹，RandomForest跟KNN

Empty DataFrame
Columns: [datetime, season, holiday, workingday, weather, temp, atemp, humidity, windspeed, casual, registered, count]
Index: []

In [ ]:
train.drop_duplicates(inplace = True)


In [ ]:
train.corr()


season   holiday  workingday   weather      temp     atemp  \
season      1.000000  0.029368   -0.008126  0.008879  0.258689  0.264744   
holiday     0.029368  1.000000   -0.250491 -0.007074  0.000295 -0.005215   
workingday -0.008126 -0.250491    1.000000  0.033772  0.029966  0.024660   
weather     0.008879 -0.007074    0.033772  1.000000 -0.055035 -0.055376   
temp        0.258689  0.000295    0.029966 -0.055035  1.000000  0.984948   
atemp       0.264744 -0.005215    0.024660 -0.055376  0.984948  1.000000   
humidity    0.190610  0.001929   -0.010880  0.406244 -0.064949 -0.043536   
windspeed  -0.147121  0.008409    0.013373  0.007261 -0.017852 -0.057473   
casual      0.096758  0.043799   -0.319111 -0.135918  0.467097  0.462067   
registered  0.164011 -0.020956    0.119460 -0.109340  0.318571  0.314635   
count       0.163439 -0.005393    0.011594 -0.128655  0.394454  0.389784   

            humidity  windspeed    casual  registered     count  
season      0.190610  -0.147121  0.096758    0.164011  0.163439  
holiday     0.001929   0.008409  0.043799   -0.020956 -0.005393  
workingday -0.010880   0.013373 -0.319111    0.119460  0.011594  
weather     0.406244   0.007261 -0.135918   -0.109340 -0.128655  
temp       -0.064949  -0.017852  0.467097    0.318571  0.394454  
atemp      -0.043536  -0.057473  0.462067    0.314635  0.389784  
humidity    1.000000  -0.318607 -0.348187   -0.265458 -0.317371  
windspeed  -0.318607   1.000000  0.092276    0.091052  0.101369  
casual     -0.348187   0.092276  1.000000    0.497250  0.690414  
registered -0.265458   0.091052  0.497250    1.000000  0.970948  
count      -0.317371   0.101369  0.690414    0.970948  1.000000

In [ ]:
X = train[["season","workingday","temp","atemp","windspeed"]].values
X[0:3]

array([[ 1.   ,  0.   ,  9.84 , 14.395,  0.   ],
       [ 1.   ,  0.   ,  9.02 , 13.635,  0.   ],
       [ 1.   ,  0.   ,  9.02 , 13.635,  0.   ]])

In [ ]:
Y = train[["count"]].values
Y[0:3]

array([[16],
       [40],
       [32]])

In [ ]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[-1.34986372, -1.46067232, -1.33366069, -1.09273697, -1.56775367],
       [-1.34986372, -1.46067232, -1.43890721, -1.18242083, -1.56775367],
       [-1.34986372, -1.46067232, -1.43890721, -1.18242083, -1.56775367],
       [-1.34986372, -1.46067232, -1.33366069, -1.09273697, -1.56775367],
       [-1.34986372, -1.46067232, -1.33366069, -1.09273697, -1.56775367]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_temp, Y_train, Y_temp = train_test_split(
    X, Y, train_size=0.6, random_state=0)

X_test, X_vali, Y_test, Y_vali = train_test_split(
    X_temp, Y_temp, test_size=0.5, random_state=0)
#這邊再切資料，切成6:2:2


In [ ]:
#決策樹
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

model = DecisionTreeClassifier(criterion='entropy', max_depth=13)

model.fit(X_train, Y_train)
y_pred = model.predict(X_test)

print('Decision Tree')
print('Accuracy: ' + str(accuracy_score(Y_test, y_pred)))
#這邊是在用決策樹演算法跟算印出成功率

Decision Tree
Accuracy: 0.007349563619660083


In [ ]:
#RandomForest
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100)

model.fit(X_train, Y_train)
y_pred = model.predict(X_test)

print('Random Forest')
print('Accuracy: ' + str(accuracy_score(Y_test, y_pred)))
#這邊是在用RandomForest演算法跟印出成功率

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


Random Forest
Accuracy: 0.0036747818098300414


In [ ]:
from sklearn.neighbors import KNeighborsRegressor
from math import sqrt
from sklearn.metrics import mean_squared_error

In [ ]:
length = round(sqrt(train.shape[0]))

In [ ]:
rmse_dict = {}
rmse_list = []
for k in range(1,length+1):
    model = KNeighborsRegressor(n_neighbors = k).fit(X_train,Y_train)
    Y_predict = model.predict(X_test)
    rmse = sqrt(mean_squared_error(Y_test,Y_predict))
    rmse_dict.update({k:rmse})
    rmse_list.append(rmse)
    print("Rmse for k = {} is {}" .format(k,rmse))
    #這邊是KNN演算法的過程，我把它印出來

Rmse for k = 1 is 210.40814287248105
Rmse for k = 2 is 187.68442682975677
Rmse for k = 3 is 175.99938463536674
Rmse for k = 4 is 170.8219863207456
Rmse for k = 5 is 166.4337132047909
Rmse for k = 6 is 164.62666221332134
Rmse for k = 7 is 163.26889260038055
Rmse for k = 8 is 162.46043653303664
Rmse for k = 9 is 161.9380876151177
Rmse for k = 10 is 161.111093977616
Rmse for k = 11 is 160.59850324550249
Rmse for k = 12 is 160.43994754377965
Rmse for k = 13 is 160.20647879545996
Rmse for k = 14 is 159.6846317530985
Rmse for k = 15 is 159.18061608991167
Rmse for k = 16 is 159.41341683492135
Rmse for k = 17 is 159.45173090965267
Rmse for k = 18 is 159.42267971545976
Rmse for k = 19 is 159.0083133891109
Rmse for k = 20 is 159.01085901750426
Rmse for k = 21 is 158.8281126490274
Rmse for k = 22 is 158.4597891953412
Rmse for k = 23 is 158.5512511262426
Rmse for k = 24 is 158.8786720363546
Rmse for k = 25 is 159.1222509126476
Rmse for k = 26 is 159.09935028624335
Rmse for k = 27 is 159.2347818002

In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=69)

model.fit(X_train, Y_train)
y_pred = model.predict(X_test)

print('kNN')
print('Accuracy: ' + str(accuracy_score(Y_test, y_pred)))
#這邊是在印出KNN的成功率


kNN
Accuracy: 0.015617822691777675


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [ ]:
key_min = min(rmse_dict.keys(), key=(lambda k: rmse_dict[k]))

print( "The miminum RMSE value is ",rmse_dict[key_min], "with k= ", key_min) 
#這是KNN的最小值

The miminum RMSE value is  158.4597891953412 with k=  22
